tasks:
  - init: ./gradlew --warning-mode all clean shadowJar
    command: ./gitpod-init-repl.sh
    name: REPL
    
image: gitpod/workspace-java-21

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
